### ISSUE TITLE
file input support for payloads in config file

### ISSUE THREAD

**Issue by zy9ard3** [projectdiscovery/alterx#13]
Hi @projectdiscovery team,

An Awesome & Nice tool to work with : )

And It will be great and more helpful if implement support for loading wordlists file on [permutations.yaml](https://github.com/projectdiscovery/alterx/blob/main/permutations.yaml) for payloads just like loading files on other yaml configs

#### Example permutations.yaml :
```yaml
patterns:
  - "{{word}}-{{sub}}.{{suffix}}"
  - "{{sub}}-{{word}}.{{suffix}}"

payloads:
   word: /path/to/wordlists.txt
```

Thanks & Regards,
@zy9ard3
