### ISSUE TITLE
Expected output is missing

### ISSUE THREAD

**Issue by meme-lord** [projectdiscovery/alterx#168]
test_subs.txt:
```
abc.site.com
xyz.site.com
def.ghi.site.com
```
test.yml:
```yml
patterns:
  - "{{word}}-{{sub}}.{{suffix}}"

payloads:
  word:
    - "1"
    - "a"
    - "ab"
```
Command:
```sh
alterx -l test_subs.txt -ac test.yml | sort
```
Output:
```
1-abc.site.com
1-def.ghi.site.com
1-xyz.site.com
ab-def.ghi.site.com
ab-xyz.site.com
a-def.ghi.site.com
a-xyz.site.com
```
Missing:
```
a-abc.site.com
ab-abc.site.com
```
